import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { CardDTO } from '@/lib/server/cards';
import { CollectionNode } from '@/lib/types';
import { ENHANCED_DEMO_CARDS, ENHANCED_DEMO_COLLECTIONS } from './demo-data-enhanced';

type DemoDataStore = {
  cards: CardDTO[];
  collections: CollectionNode[];
  isInitialized: boolean;

  initialize: () => void;
  addCard: (cardData: Partial<CardDTO>) => void;
  updateCard: (id: string, updates: Partial<CardDTO>) => void;
  deleteCard: (id: string) => void;
  addCollection: (collectionData: { name: string; parentId?: string | null }) => void;
  updateCollection: (id: string, updates: { name?: string; parentId?: string | null; pinned?: boolean; hidePreview?: boolean; useCoverAsBackground?: boolean; isPrivate?: boolean }) => void;
  deleteCollection: (id: string, deleteCards?: boolean, deleteSubPawkits?: boolean) => void;
  reset: () => void;
};

// Demo cards showcasing various features with high-quality images
const DEMO_CARDS: CardDTO[] = [
  {
    id: 'demo-1',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    title: 'How I organize 10,000+ bookmarks with Pawkit',
    description: 'A deep dive into my personal bookmark management system',
    domain: 'youtube.com',
    image: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-1'],
    tags: ['productivity', 'tutorial'],
    notes: 'Great tips on organizing bookmarks at scale!',
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date('2025-01-15').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: true,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-2',
    url: 'https://www.tiktok.com/@productivityhacks',
    title: '5 Browser Extensions That Changed My Life',
    description: 'Must-have browser extensions for productivity',
    domain: 'tiktok.com',
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-2'],
    tags: ['tools', 'productivity'],
    notes: null,
    createdAt: new Date('2025-01-14').toISOString(),
    updatedAt: new Date('2025-01-14').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-3',
    url: 'https://www.nytimes.com/2025/01/01/technology/ai-future.html',
    title: 'The Future of AI: What 2025 Holds',
    description: 'An in-depth analysis of AI trends and predictions for the coming year',
    domain: 'nytimes.com',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['ai', 'technology', 'read-later'],
    notes: null,
    content: null,
    articleContent: '<article><h1>The Future of AI: What 2025 Holds</h1><p>This is a sample article showcasing reader mode. The real content would be extracted from the actual webpage...</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></article>',
    createdAt: new Date('2025-01-13').toISOString(),
    updatedAt: new Date('2025-01-13').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: new Date('2025-02-01').toISOString(),
  },
  {
    id: 'demo-4',
    url: 'https://github.com/vercel/next.js',
    title: 'Next.js - The React Framework for the Web',
    description: 'Used by some of the world\'s largest companies, Next.js enables you to create high-quality web applications',
    domain: 'github.com',
    image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-3'],
    tags: ['github', 'open-source', 'nextjs'],
    notes: 'Amazing framework for React apps!',
    createdAt: new Date('2025-01-12').toISOString(),
    updatedAt: new Date('2025-01-12').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-5',
    url: 'https://www.reddit.com/r/productivity/comments/example',
    title: 'My 2025 Productivity System (Complete Guide)',
    description: 'How I stay productive using a simple bookmark-first workflow',
    domain: 'reddit.com',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-1'],
    tags: ['productivity', 'workflow'],
    notes: 'Love the idea of using bookmarks as a task manager!',
    createdAt: new Date('2025-01-11').toISOString(),
    updatedAt: new Date('2025-01-11').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-6',
    url: 'https://www.notion.so/templates/reading-list',
    title: 'Ultimate Reading List Template',
    description: 'Track your reading with this comprehensive Notion template',
    domain: 'notion.so',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-2'],
    tags: ['notion', 'templates', 'reading'],
    notes: null,
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-01-10').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-7',
    url: 'https://www.instagram.com/p/example',
    title: 'Beautiful Workspace Setup Ideas',
    description: 'Inspiration for your home office',
    domain: 'instagram.com',
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-3'],
    tags: ['design', 'workspace'],
    notes: 'Love the minimalist aesthetic!',
    createdAt: new Date('2025-01-09').toISOString(),
    updatedAt: new Date('2025-01-09').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-8',
    url: 'https://twitter.com/example/status/123',
    title: 'Thread: How to Build a Second Brain in 2025',
    description: 'A comprehensive thread on personal knowledge management',
    domain: 'twitter.com',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['pkm', 'learning'],
    notes: 'Amazing thread! Need to implement these ideas.',
    createdAt: new Date('2025-01-08').toISOString(),
    updatedAt: new Date('2025-01-08').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-9',
    url: 'https://medium.com/@author/minimalist-life',
    title: 'Why I Deleted 90% of My Bookmarks',
    description: 'The case for digital minimalism and intentional bookmarking',
    domain: 'medium.com',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-1'],
    tags: ['minimalism', 'productivity'],
    notes: null,
    content: null,
    articleContent: '<article><h1>Why I Deleted 90% of My Bookmarks</h1><p>Sample article content showcasing reader mode functionality...</p></article>',
    createdAt: new Date('2025-01-07').toISOString(),
    updatedAt: new Date('2025-01-07').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-10',
    url: 'https://www.spotify.com/playlist/example',
    title: 'Deep Focus - Productivity Playlist',
    description: '2 hours of ambient music for deep work',
    domain: 'spotify.com',
    image: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-2'],
    tags: ['music', 'focus'],
    notes: 'Perfect for coding sessions!',
    createdAt: new Date('2025-01-06').toISOString(),
    updatedAt: new Date('2025-01-06').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-11',
    url: '',
    title: 'Meeting Notes - Q1 Planning',
    description: null,
    domain: null,
    image: null,
    type: 'md-note',
    status: 'READY',
    collections: [],
    tags: ['notes', 'work'],
    notes: null,
    content: '# Q1 Planning Meeting\n\n## Goals\n- Launch new feature set\n- Improve user onboarding\n- Reduce churn by 15%\n\n## Action Items\n- [ ] Review analytics\n- [ ] Schedule user interviews\n- [ ] Create roadmap',
    articleContent: null,
    createdAt: new Date('2025-01-05').toISOString(),
    updatedAt: new Date('2025-01-05').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-12',
    url: 'https://www.theverge.com/2025/1/4/tech-trends',
    title: 'The Biggest Tech Trends of 2025',
    description: 'What to expect from technology this year',
    domain: 'theverge.com',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-3'],
    tags: ['technology', 'trends'],
    notes: null,
    createdAt: new Date('2025-01-04').toISOString(),
    updatedAt: new Date('2025-01-04').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-13',
    url: 'https://www.figma.com/community/file/example',
    title: 'Free UI Design System 2025',
    description: 'A comprehensive design system for modern web apps',
    domain: 'figma.com',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-3'],
    tags: ['design', 'ui', 'figma'],
    notes: 'Check out the component library!',
    createdAt: new Date('2025-01-03').toISOString(),
    updatedAt: new Date('2025-01-03').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-14',
    url: 'https://www.producthunt.com/posts/example',
    title: 'Awesome AI Writing Tool - Product Hunt',
    description: 'Write better content 10x faster with AI',
    domain: 'producthunt.com',
    image: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-2'],
    tags: ['ai', 'writing', 'tools'],
    notes: 'Might be useful for blog posts',
    createdAt: new Date('2025-01-02').toISOString(),
    updatedAt: new Date('2025-01-02').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-15',
    url: 'https://news.ycombinator.com/item?id=123',
    title: 'Ask HN: Best Bookmark Manager in 2025?',
    description: 'Discussion about bookmark management tools',
    domain: 'news.ycombinator.com',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['hn', 'discussion'],
    notes: 'Lots of good recommendations in the comments',
    createdAt: new Date('2025-01-01').toISOString(),
    updatedAt: new Date('2025-01-01').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-16',
    url: 'https://www.substack.com/example/building-habits',
    title: 'Building Habits That Stick: A Scientific Approach',
    description: 'Evidence-based strategies for habit formation',
    domain: 'substack.com',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-1'],
    tags: ['habits', 'self-improvement'],
    notes: null,
    content: null,
    articleContent: '<article><h1>Building Habits That Stick</h1><p>Demo article with reader mode enabled...</p></article>',
    createdAt: new Date('2024-12-31').toISOString(),
    updatedAt: new Date('2024-12-31').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-17',
    url: 'https://www.linkedin.com/posts/example',
    title: 'Career Advice: What I Wish I Knew at 25',
    description: 'Lessons learned from 15 years in tech',
    domain: 'linkedin.com',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['career', 'advice'],
    notes: 'Great insights on career progression',
    createdAt: new Date('2024-12-30').toISOString(),
    updatedAt: new Date('2024-12-30').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-18',
    url: 'https://www.pinterest.com/pin/example',
    title: 'Minimalist Home Office Ideas',
    description: 'Curated collection of workspace inspiration',
    domain: 'pinterest.com',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-3'],
    tags: ['design', 'workspace', 'inspiration'],
    notes: null,
    createdAt: new Date('2024-12-29').toISOString(),
    updatedAt: new Date('2024-12-29').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-19',
    url: 'https://www.twitch.tv/example/clip/abc',
    title: 'Insane Coding Speed Run - React App in 30 Minutes',
    description: 'Watch a developer build a full app from scratch',
    domain: 'twitch.tv',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['demo-col-2'],
    tags: ['coding', 'tutorial', 'react'],
    notes: 'Need to try this challenge myself!',
    createdAt: new Date('2024-12-28').toISOString(),
    updatedAt: new Date('2024-12-28').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'demo-20',
    url: '',
    title: 'Book Recommendations 2025',
    description: null,
    domain: null,
    image: null,
    type: 'text-note',
    status: 'READY',
    collections: [],
    tags: ['books', 'reading'],
    notes: null,
    content: 'Must-read books:\n- Atomic Habits\n- Deep Work\n- The Pragmatic Programmer\n- Designing Data-Intensive Applications\n- System Design Interview',
    articleContent: null,
    createdAt: new Date('2024-12-27').toISOString(),
    updatedAt: new Date('2024-12-27').toISOString(),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
];

const DEMO_COLLECTIONS: CollectionNode[] = [
  {
    id: 'demo-col-1',
    name: 'Productivity & Workflows',
    slug: 'productivity-workflows',
    parentId: null,
    pinned: true,
    deleted: false,
    userId: 'demo-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    children: [],
  },
  {
    id: 'demo-col-2',
    name: 'Tools & Resources',
    slug: 'tools-resources',
    parentId: null,
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    children: [],
  },
  {
    id: 'demo-col-3',
    name: 'Design Inspiration',
    slug: 'design-inspiration',
    parentId: null,
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    children: [],
  },
];

export const useDemoDataStore = create<DemoDataStore>()(
  persist(
    (set, get) => ({
      cards: [],
      collections: [],
      isInitialized: false,

      initialize: () => {
        if (get().isInitialized) {
          return;
        }

        set({
          cards: ENHANCED_DEMO_CARDS,
          collections: ENHANCED_DEMO_COLLECTIONS,
          isInitialized: true,
        });
      },

      addCard: (cardData: Partial<CardDTO>) => {
        const newCard: CardDTO = {
          id: `demo-${Date.now()}`,
          url: cardData.url || '',
          title: cardData.title || null,
          notes: cardData.notes || null,
          content: cardData.content || null,
          type: (cardData.type as 'url' | 'md-note' | 'text-note') || 'url',
          status: 'READY',
          collections: cardData.collections || [],
          tags: cardData.tags || [],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          userId: 'demo-user',
          deleted: false,
          deletedAt: null,
          pinned: false,
          domain: null,
          image: null,
          description: null,
          articleContent: null,
          metadata: undefined,
          inDen: false,
          encryptedContent: null,
          scheduledDate: null,
        };

        set((state) => ({
          cards: [newCard, ...state.cards],
        }));
      },

      updateCard: (id: string, updates: Partial<CardDTO>) => {
        set((state) => ({
          cards: state.cards.map((c) => (c.id === id ? { ...c, ...updates } : c)),
        }));
      },

      deleteCard: (id: string) => {
        set((state) => ({
          cards: state.cards.filter((c) => c.id !== id),
        }));
      },

      addCollection: (collectionData: { name: string; parentId?: string | null }) => {
        const slug = collectionData.name.toLowerCase().replace(/\s+/g, '-');
        const newCollection: CollectionNode = {
          id: `demo-col-${Date.now()}`,
          name: collectionData.name,
          slug,
          parentId: collectionData.parentId || null,
          pinned: false,
          deleted: false,
          userId: 'demo-user',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          children: [],
        };

        set((state) => ({
          collections: [...state.collections, newCollection],
        }));
      },

      updateCollection: (id: string, updates: { name?: string; parentId?: string | null; pinned?: boolean; hidePreview?: boolean; useCoverAsBackground?: boolean; isPrivate?: boolean }) => {
        set((state) => ({
          collections: state.collections.map((c) => (c.id === id ? { ...c, ...updates } : c)),
        }));
      },

      deleteCollection: (id: string, deleteCards?: boolean, deleteSubPawkits?: boolean) => {
        set((state) => ({
          collections: state.collections.filter((c) => c.id !== id),
          cards: deleteCards
            ? state.cards.filter((card) => !card.collections?.includes(id))
            : state.cards.map((card) => ({
                ...card,
                collections: card.collections?.filter((cId) => cId !== id) || [],
              })),
        }));
      },

      reset: () => {
        set({
          cards: ENHANCED_DEMO_CARDS,
          collections: ENHANCED_DEMO_COLLECTIONS,
          isInitialized: true,
        });
      },
    }),
    {
      name: 'pawkit-demo-storage',
    }
  )
);
