import { CardDTO } from '@/lib/server/cards';
import { CollectionNode } from '@/lib/types';

/**
 * Enhanced Demo Data for Pawkit Screenshots & Demos
 * 50+ cards across various categories, nested collections, and Den items
 */

// Helper to generate dates going back 60 days
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const ENHANCED_DEMO_COLLECTIONS: CollectionNode[] = [
  // Top-level collections
  {
    id: 'col-productivity',
    name: 'Productivity & Workflows',
    slug: 'productivity-workflows',
    parentId: null,
    pinned: true,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
    children: [],
  },
  {
    id: 'col-development',
    name: 'Development',
    slug: 'development',
    parentId: null,
    pinned: true,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(58),
    updatedAt: daysAgo(2),
    children: [],
  },
  {
    id: 'col-design',
    name: 'Design & Inspiration',
    slug: 'design-inspiration',
    parentId: null,
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
    children: [],
  },
  {
    id: 'col-reading',
    name: 'Reading List',
    slug: 'reading-list',
    parentId: null,
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
    children: [],
  },
  {
    id: 'col-learning',
    name: 'Learning & Courses',
    slug: 'learning-courses',
    parentId: null,
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(7),
    children: [],
  },

  // Nested collections under Development
  {
    id: 'col-dev-frontend',
    name: 'Frontend',
    slug: 'frontend',
    parentId: 'col-development',
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(57),
    updatedAt: daysAgo(2),
    children: [],
  },
  {
    id: 'col-dev-backend',
    name: 'Backend & APIs',
    slug: 'backend-apis',
    parentId: 'col-development',
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(56),
    updatedAt: daysAgo(4),
    children: [],
  },
  {
    id: 'col-dev-tools',
    name: 'Dev Tools',
    slug: 'dev-tools',
    parentId: 'col-development',
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(54),
    updatedAt: daysAgo(6),
    children: [],
  },

  // Nested collections under Design
  {
    id: 'col-design-ui',
    name: 'UI/UX',
    slug: 'ui-ux',
    parentId: 'col-design',
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(53),
    updatedAt: daysAgo(8),
    children: [],
  },
  {
    id: 'col-design-colors',
    name: 'Color Palettes',
    slug: 'color-palettes',
    parentId: 'col-design',
    pinned: false,
    deleted: false,
    userId: 'demo-user',
    createdAt: daysAgo(52),
    updatedAt: daysAgo(10),
    children: [],
  },
];

export const ENHANCED_DEMO_CARDS: CardDTO[] = [
  // Productivity & Workflows
  {
    id: 'card-1',
    url: 'https://www.youtube.com/watch?v=example1',
    title: 'The Ultimate GTD System for 2025',
    description: 'How to implement Getting Things Done in the modern age',
    domain: 'youtube.com',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-productivity'],
    tags: ['gtd', 'productivity', 'systems'],
    notes: 'Great breakdown of the GTD workflow!',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: true,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-2',
    url: 'https://todoist.com/productivity-methods/eat-the-frog',
    title: 'Eat That Frog! - Productivity Method',
    description: 'Tackle your biggest task first thing in the morning',
    domain: 'todoist.com',
    image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-productivity'],
    tags: ['productivity', 'time-management'],
    notes: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-3',
    url: 'https://www.notion.so/templates/weekly-planner',
    title: 'Notion Weekly Planner Template',
    description: 'A beautiful template for planning your week ahead',
    domain: 'notion.so',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-productivity'],
    tags: ['notion', 'templates', 'planning'],
    notes: 'Using this for my Sunday reviews',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Frontend Development
  {
    id: 'card-4',
    url: 'https://react.dev/learn',
    title: 'React 19 Documentation',
    description: 'The library for web and native user interfaces',
    domain: 'react.dev',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['react', 'javascript', 'docs'],
    notes: 'Check out the new hooks!',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: true,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-5',
    url: 'https://tailwindcss.com/docs',
    title: 'Tailwind CSS Documentation',
    description: 'Rapidly build modern websites without ever leaving your HTML',
    domain: 'tailwindcss.com',
    image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['css', 'tailwind', 'styling'],
    notes: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-6',
    url: 'https://ui.shadcn.com/',
    title: 'shadcn/ui - Beautifully designed components',
    description: 'Copy-paste components built with Radix UI and Tailwind CSS',
    domain: 'ui.shadcn.com',
    image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['components', 'ui', 'react'],
    notes: 'Love the component library!',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Backend & APIs
  {
    id: 'card-7',
    url: 'https://nextjs.org/docs',
    title: 'Next.js 15 Documentation',
    description: 'The React Framework for the Web',
    domain: 'nextjs.org',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['nextjs', 'react', 'framework'],
    notes: 'Server components are game-changing',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: true,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-8',
    url: 'https://supabase.com/docs',
    title: 'Supabase - Open Source Firebase Alternative',
    description: 'Build production-grade apps with a Postgres database',
    domain: 'supabase.com',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['database', 'postgres', 'backend'],
    notes: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-9',
    url: 'https://www.prisma.io/docs',
    title: 'Prisma ORM Documentation',
    description: 'Next-generation Node.js and TypeScript ORM',
    domain: 'prisma.io',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['orm', 'database', 'typescript'],
    notes: 'Great for type-safe queries',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Dev Tools
  {
    id: 'card-10',
    url: 'https://github.com/features/copilot',
    title: 'GitHub Copilot - Your AI pair programmer',
    description: 'Code faster with AI-powered code completions',
    domain: 'github.com',
    image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-tools'],
    tags: ['ai', 'github', 'tools'],
    notes: 'Saves so much time!',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-11',
    url: 'https://code.visualstudio.com/docs',
    title: 'VS Code Documentation',
    description: 'Code editing. Redefined.',
    domain: 'code.visualstudio.com',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-tools'],
    tags: ['vscode', 'editor', 'tools'],
    notes: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Design & UI/UX
  {
    id: 'card-12',
    url: 'https://www.figma.com/community',
    title: 'Figma Community Resources',
    description: 'Thousands of free design resources and plugins',
    domain: 'figma.com',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['figma', 'design', 'ui'],
    notes: 'Check out the mobile UI kits',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-13',
    url: 'https://dribbble.com/shots/popular',
    title: 'Dribbble - Discover the World's Top Designers',
    description: 'Inspiration for your next design project',
    domain: 'dribbble.com',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['design', 'inspiration', 'ui'],
    notes: null,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-14',
    url: 'https://www.behance.net/',
    title: 'Behance - Creative Portfolio Showcase',
    description: 'Showcase and discover creative work',
    domain: 'behance.net',
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['design', 'portfolio', 'inspiration'],
    notes: 'Great for finding UX case studies',
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Color Palettes
  {
    id: 'card-15',
    url: 'https://coolors.co/',
    title: 'Coolors - The super fast color palette generator',
    description: 'Create the perfect color scheme for your designs',
    domain: 'coolors.co',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-colors'],
    tags: ['colors', 'design', 'tools'],
    notes: 'Use this for every project',
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-16',
    url: 'https://www.happyhues.co/',
    title: 'Happy Hues - Curated color palettes',
    description: 'See color palette inspiration in real designs',
    domain: 'happyhues.co',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-colors'],
    tags: ['colors', 'inspiration'],
    notes: null,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Reading List - Articles with reader mode
  {
    id: 'card-17',
    url: 'https://www.nytimes.com/2025/01/15/technology/ai-trends.html',
    title: 'The AI Revolution: What Comes Next',
    description: 'An in-depth look at the future of artificial intelligence',
    domain: 'nytimes.com',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-reading'],
    tags: ['ai', 'technology', 'read-later'],
    notes: null,
    content: null,
    articleContent: '<article><h1>The AI Revolution: What Comes Next</h1><p>Artificial intelligence continues to reshape our world at an unprecedented pace. From healthcare to transportation, AI systems are becoming more sophisticated and integrated into daily life...</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. The implications for society are profound and far-reaching.</p></article>',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: daysAgo(-7), // Scheduled for 7 days from now
  },
  {
    id: 'card-18',
    url: 'https://www.theverge.com/2025/1/10/tech-review',
    title: 'The Best Tech of 2025 (So Far)',
    description: 'Our favorite gadgets and apps of the year',
    domain: 'theverge.com',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-reading'],
    tags: ['technology', 'gadgets', 'reviews'],
    notes: 'Want to check out that new laptop',
    content: null,
    articleContent: '<article><h1>The Best Tech of 2025</h1><p>This year has already brought incredible innovations...</p></article>',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Learning & Courses
  {
    id: 'card-19',
    url: 'https://www.youtube.com/watch?v=example-course',
    title: 'Complete TypeScript Course 2025',
    description: 'Learn TypeScript from beginner to advanced',
    domain: 'youtube.com',
    image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['typescript', 'course', 'learning'],
    notes: 'On chapter 5/12',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-20',
    url: 'https://frontendmasters.com/courses/web-performance/',
    title: 'Web Performance Fundamentals',
    description: 'Optimize your web apps for speed',
    domain: 'frontendmasters.com',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['performance', 'course', 'web'],
    notes: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Uncategorized items (showcasing flexibility)
  {
    id: 'card-21',
    url: 'https://github.com/awesome-selfhosted/awesome-selfhosted',
    title: 'Awesome Self-Hosted',
    description: 'Free Software network services and web applications',
    domain: 'github.com',
    image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['self-hosted', 'open-source'],
    notes: 'Bookmark manager ideas here!',
    createdAt: daysAgo(22),
    updatedAt: daysAgo(22),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Notes (showcasing different note types)
  {
    id: 'note-1',
    url: '',
    title: 'Project Ideas for 2025',
    description: null,
    domain: null,
    image: null,
    type: 'md-note',
    status: 'READY',
    collections: [],
    tags: ['ideas', 'projects'],
    notes: null,
    content: '# Project Ideas for 2025\n\n## Web Apps\n- [ ] Build a local-first task manager\n- [ ] Create a markdown-based wiki\n- [ ] Develop a privacy-focused bookmark tool\n\n## Learning Goals\n- Master Rust programming\n- Deep dive into system design\n- Build something with Web3\n\n## Side Projects\n- Contribute to open source\n- Write technical blog posts\n- Launch a SaaS product',
    articleContent: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'note-2',
    url: '',
    title: 'Book Recommendations',
    description: null,
    domain: null,
    image: null,
    type: 'text-note',
    status: 'READY',
    collections: ['col-reading'],
    tags: ['books', 'reading'],
    notes: null,
    content: 'Must-read books:\n• Atomic Habits - James Clear\n• Deep Work - Cal Newport\n• The Pragmatic Programmer - Hunt & Thomas\n• Designing Data-Intensive Applications - Martin Kleppmann\n• Clean Code - Robert Martin\n\nCurrently Reading:\n• System Design Interview by Alex Xu',
    articleContent: null,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(5),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },

  // Den items (encrypted/private) - these showcase The Den feature
  {
    id: 'den-1',
    url: 'https://www.example.com/private-financial-planning',
    title: '2025 Financial Goals',
    description: 'Personal finance planning and investment strategies',
    domain: 'example.com',
    image: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['finance', 'private'],
    notes: 'Encrypted note content here',
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: true,
    encryptedContent: 'encrypted_demo_content_123',
    scheduledDate: null,
  },
  {
    id: 'den-2',
    url: 'https://www.example.com/health-records',
    title: 'Medical Records Portal',
    description: 'Access to health insurance and medical history',
    domain: 'example.com',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['health', 'private'],
    notes: null,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(35),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: true,
    encryptedContent: 'encrypted_demo_content_456',
    scheduledDate: null,
  },
  {
    id: 'den-note-1',
    url: '',
    title: 'Personal Journal Entry',
    description: null,
    domain: null,
    image: null,
    type: 'md-note',
    status: 'READY',
    collections: [],
    tags: ['journal', 'private'],
    notes: null,
    content: 'This content would be encrypted in The Den...',
    articleContent: null,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    metadata: undefined,
    inDen: true,
    encryptedContent: 'encrypted_demo_content_789',
    scheduledDate: null,
  },

  // Additional diverse content to reach 50+
  {
    id: 'card-22',
    url: 'https://www.reddit.com/r/webdev',
    title: 'r/webdev - Web Development Community',
    description: 'A community dedicated to all things web development',
    domain: 'reddit.com',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-development'],
    tags: ['reddit', 'community', 'webdev'],
    notes: null,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-23',
    url: 'https://twitter.com/dan_abramov',
    title: 'Dan Abramov (@dan_abramov) on Twitter',
    description: 'Working on @reactjs. Co-author of Redux and Create React App.',
    domain: 'twitter.com',
    image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['twitter', 'react', 'influencer'],
    notes: 'Great insights on React internals',
    createdAt: daysAgo(24),
    updatedAt: daysAgo(24),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-24',
    url: 'https://www.producthunt.com/',
    title: 'Product Hunt - The best new products in tech',
    description: 'Discover new products every day',
    domain: 'producthunt.com',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-productivity'],
    tags: ['products', 'discovery', 'startup'],
    notes: 'Daily morning routine',
    createdAt: daysAgo(26),
    updatedAt: daysAgo(2),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-25',
    url: 'https://medium.com/better-programming',
    title: 'Better Programming on Medium',
    description: 'Advice for programmers',
    domain: 'medium.com',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-reading'],
    tags: ['programming', 'articles', 'medium'],
    notes: null,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(27),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-26',
    url: 'https://news.ycombinator.com/',
    title: 'Hacker News',
    description: 'Social news website focusing on computer science and entrepreneurship',
    domain: 'news.ycombinator.com',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: [],
    tags: ['news', 'tech', 'community'],
    notes: 'Check daily',
    createdAt: daysAgo(29),
    updatedAt: daysAgo(1),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: true,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-27',
    url: 'https://www.typescriptlang.org/docs/',
    title: 'TypeScript Documentation',
    description: 'TypeScript is JavaScript with syntax for types',
    domain: 'typescriptlang.org',
    image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['typescript', 'docs', 'javascript'],
    notes: 'Reference for advanced types',
    createdAt: daysAgo(31),
    updatedAt: daysAgo(31),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-28',
    url: 'https://developer.mozilla.org/en-US/',
    title: 'MDN Web Docs',
    description: 'Resources for developers, by developers',
    domain: 'developer.mozilla.org',
    image: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['docs', 'web', 'reference'],
    notes: 'The best web docs',
    createdAt: daysAgo(32),
    updatedAt: daysAgo(32),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-29',
    url: 'https://www.patterns.dev/',
    title: 'Patterns.dev - Modern Web App Design Patterns',
    description: 'Free book on design patterns and component patterns',
    domain: 'patterns.dev',
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['patterns', 'architecture', 'web'],
    notes: 'Must read for senior devs',
    createdAt: daysAgo(33),
    updatedAt: daysAgo(33),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-30',
    url: 'https://css-tricks.com/',
    title: 'CSS-Tricks',
    description: 'Daily articles about CSS, HTML, JavaScript, and web design',
    domain: 'css-tricks.com',
    image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['css', 'articles', 'tutorials'],
    notes: null,
    createdAt: daysAgo(34),
    updatedAt: daysAgo(34),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  // Continue with more cards...
  {
    id: 'card-31',
    url: 'https://fonts.google.com/',
    title: 'Google Fonts',
    description: 'Making the web more beautiful with free fonts',
    domain: 'fonts.google.com',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design'],
    tags: ['fonts', 'typography', 'design'],
    notes: 'Inter and Poppins are my go-to',
    createdAt: daysAgo(36),
    updatedAt: daysAgo(36),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-32',
    url: 'https://unsplash.com/',
    title: 'Unsplash - Beautiful Free Images & Pictures',
    description: 'Over 3 million free high-resolution images',
    domain: 'unsplash.com',
    image: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design'],
    tags: ['images', 'photography', 'free'],
    notes: 'Best free stock photos',
    createdAt: daysAgo(37),
    updatedAt: daysAgo(37),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-33',
    url: 'https://www.framer.com/',
    title: 'Framer - Design and ship your dream site',
    description: 'The web builder for creative pros',
    domain: 'framer.com',
    image: 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['design', 'tools', 'web-builder'],
    notes: 'Great for landing pages',
    createdAt: daysAgo(38),
    updatedAt: daysAgo(38),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-34',
    url: 'https://www.svgrepo.com/',
    title: 'SVG Repo - Free SVG Vectors and Icons',
    description: '500,000+ open-licensed SVG vectors and icons',
    domain: 'svgrepo.com',
    image: 'https://images.unsplash.com/photo-1618556450991-2f1af64e8191?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design'],
    tags: ['svg', 'icons', 'free'],
    notes: null,
    createdAt: daysAgo(39),
    updatedAt: daysAgo(39),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-35',
    url: 'https://vercel.com/docs',
    title: 'Vercel Documentation',
    description: 'Build and deploy modern web apps',
    domain: 'vercel.com',
    image: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-tools'],
    tags: ['hosting', 'deployment', 'vercel'],
    notes: 'Best hosting for Next.js',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(40),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-36',
    url: 'https://railway.app/',
    title: 'Railway - Instant Deployments',
    description: 'Made for any language, for projects big and small',
    domain: 'railway.app',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-tools'],
    tags: ['hosting', 'deployment', 'backend'],
    notes: 'Good alternative to Heroku',
    createdAt: daysAgo(41),
    updatedAt: daysAgo(41),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-37',
    url: 'https://planetscale.com/',
    title: 'PlanetScale - The MySQL-compatible serverless database',
    description: 'The database for developers',
    domain: 'planetscale.com',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['database', 'mysql', 'serverless'],
    notes: null,
    createdAt: daysAgo(42),
    updatedAt: daysAgo(42),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-38',
    url: 'https://clerk.com/',
    title: 'Clerk - More than authentication',
    description: 'The most comprehensive user management platform',
    domain: 'clerk.com',
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['auth', 'authentication', 'saas'],
    notes: 'Consider for next project',
    createdAt: daysAgo(43),
    updatedAt: daysAgo(43),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-39',
    url: 'https://stripe.com/docs',
    title: 'Stripe Documentation',
    description: 'Start integrating Stripe's payments APIs',
    domain: 'stripe.com',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['payments', 'stripe', 'api'],
    notes: 'Best payment docs ever',
    createdAt: daysAgo(44),
    updatedAt: daysAgo(44),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-40',
    url: 'https://www.sanity.io/',
    title: 'Sanity - The Composable Content Cloud',
    description: 'Content is data. Unlock limitless omnichannel experiences',
    domain: 'sanity.io',
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-backend'],
    tags: ['cms', 'headless', 'content'],
    notes: 'Great for blogs',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-41',
    url: 'https://mobbin.com/',
    title: 'Mobbin - Mobile & Web Design Reference Library',
    description: 'Save hours of UI & UX research',
    domain: 'mobbin.com',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['design', 'inspiration', 'mobile'],
    notes: 'Paid but worth it',
    createdAt: daysAgo(46),
    updatedAt: daysAgo(46),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-42',
    url: 'https://www.refactoringui.com/',
    title: 'Refactoring UI - Learn UI Design',
    description: 'Make your ideas look awesome, without relying on a designer',
    domain: 'refactoringui.com',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-design-ui'],
    tags: ['design', 'ui', 'book'],
    notes: 'Best UI design book',
    createdAt: daysAgo(47),
    updatedAt: daysAgo(47),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-43',
    url: 'https://ui.aceternity.com/',
    title: 'Aceternity UI - Copy paste the most trending components',
    description: 'Beautiful Tailwind CSS and Framer Motion Components',
    domain: 'ui.aceternity.com',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['components', 'ui', 'tailwind'],
    notes: 'Amazing animations!',
    createdAt: daysAgo(48),
    updatedAt: daysAgo(48),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-44',
    url: 'https://magicui.design/',
    title: 'Magic UI - Animated components',
    description: '20+ free and open-source animated components',
    domain: 'magicui.design',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-dev-frontend'],
    tags: ['components', 'animations', 'react'],
    notes: null,
    createdAt: daysAgo(49),
    updatedAt: daysAgo(49),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-45',
    url: 'https://roadmap.sh/',
    title: 'Developer Roadmaps',
    description: 'Step by step guides and paths to learn different tools',
    domain: 'roadmap.sh',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['learning', 'career', 'roadmap'],
    notes: 'Following the backend roadmap',
    createdAt: daysAgo(50),
    updatedAt: daysAgo(2),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-46',
    url: 'https://www.frontendmentor.io/',
    title: 'Frontend Mentor - Improve your front-end skills',
    description: 'Real-world HTML, CSS and JavaScript challenges',
    domain: 'frontendmentor.io',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['learning', 'frontend', 'practice'],
    notes: null,
    createdAt: daysAgo(51),
    updatedAt: daysAgo(51),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-47',
    url: 'https://javascript.info/',
    title: 'The Modern JavaScript Tutorial',
    description: 'From the basics to advanced topics with simple explanations',
    domain: 'javascript.info',
    image: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['javascript', 'tutorial', 'learning'],
    notes: 'Best JS resource',
    createdAt: daysAgo(52),
    updatedAt: daysAgo(52),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-48',
    url: 'https://web.dev/',
    title: 'web.dev - Guidance to build modern web experiences',
    description: 'Learn and measure. By Google.',
    domain: 'web.dev',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['web', 'performance', 'google'],
    notes: 'Great for web performance tips',
    createdAt: daysAgo(53),
    updatedAt: daysAgo(53),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-49',
    url: 'https://www.joshwcomeau.com/',
    title: 'Josh W. Comeau - An Animated Guide to Flexbox & More',
    description: 'Interactive tutorials and articles about web development',
    domain: 'joshwcomeau.com',
    image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['css', 'tutorials', 'blog'],
    notes: 'Amazing visual explanations',
    createdAt: daysAgo(54),
    updatedAt: daysAgo(54),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
  {
    id: 'card-50',
    url: 'https://www.youtube.com/c/Fireship',
    title: 'Fireship - High-intensity code tutorials',
    description: '100 seconds to learn any dev concept',
    domain: 'youtube.com',
    image: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&q=80',
    type: 'url',
    status: 'READY',
    collections: ['col-learning'],
    tags: ['youtube', 'tutorials', 'quick'],
    notes: 'Best tech YouTube channel',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(1),
    userId: 'demo-user',
    deleted: false,
    deletedAt: null,
    pinned: false,
    content: null,
    articleContent: null,
    metadata: undefined,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
  },
];
