"use client";

import { useMemo, Suspense, useEffect } from "react";
import { LibraryView } from "@/components/library/library-view";
import { CardModel, CollectionNode } from "@/lib/types";
import { usePanelStore } from "@/lib/hooks/use-panel-store";

// Generate realistic fake bookmark data
const FAKE_CARDS: CardModel[] = [
  // Tech Articles
  {
    id: "card-1",
    type: "url",
    url: "https://react.dev/blog/2024/04/25/react-19",
    title: "React 19 Release Candidate - What's New",
    notes: "Key changes: Actions, use() hook, better SSR streaming. Need to test this in our app.",
    content: null,
    status: "READY",
    tags: ["react", "web-dev", "javascript"],
    collections: ["tech-articles"],
    domain: "react.dev",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop",
    description: "React 19 brings exciting new features including Actions, the use() hook, and improved server streaming capabilities.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-2",
    type: "url",
    url: "https://vercel.com/blog/vercel-ai-sdk-3",
    title: "Vercel AI SDK 3.0: Building AI Applications Made Simple",
    notes: null,
    content: null,
    status: "READY",
    tags: ["ai", "development", "typescript"],
    collections: ["tech-articles", "ai-ml"],
    domain: "vercel.com",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop",
    description: "The new Vercel AI SDK makes it easier than ever to build AI-powered applications with streaming, tool calling, and more.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-3",
    type: "url",
    url: "https://tailwindcss.com/blog/tailwindcss-v4-alpha",
    title: "Tailwind CSS v4.0 Alpha: A New Engine",
    notes: "Performance improvements look amazing! 10x faster builds.",
    content: null,
    status: "READY",
    tags: ["css", "tailwind", "web-dev"],
    collections: ["tech-articles", "design-resources"],
    domain: "tailwindcss.com",
    image: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&h=400&fit=crop",
    description: "Tailwind CSS v4.0 features a brand new engine built in Rust, delivering 10x faster build times and improved developer experience.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Design Resources
  {
    id: "card-4",
    type: "url",
    url: "https://dribbble.com/shots/23456789",
    title: "Modern Dashboard UI Design - Glassmorphism",
    notes: "Love this glassmorphism style. Could use for our redesign.",
    content: null,
    status: "READY",
    tags: ["design", "ui", "inspiration"],
    collections: ["design-resources"],
    domain: "dribbble.com",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop",
    description: "Beautiful glassmorphism dashboard design with smooth animations and modern aesthetics.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-5",
    type: "url",
    url: "https://www.figma.com/community/file/1234567890",
    title: "Free Design System - Components & Tokens",
    notes: null,
    content: null,
    status: "READY",
    tags: ["design-system", "figma", "ui"],
    collections: ["design-resources"],
    domain: "figma.com",
    image: "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=400&fit=crop",
    description: "Complete design system with components, tokens, and documentation. Ready to use in your next project.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Recipes
  {
    id: "card-6",
    type: "url",
    url: "https://www.seriouseats.com/perfect-pan-pizza",
    title: "The Best Pan Pizza You'll Ever Make",
    notes: "Tried this last weekend - absolutely incredible! The crispy edges are perfect.",
    content: null,
    status: "READY",
    tags: ["recipe", "pizza", "cooking"],
    collections: ["recipes"],
    domain: "seriouseats.com",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=400&fit=crop",
    description: "This pan pizza recipe delivers crispy, golden edges and a pillowy soft center. Better than delivery!",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-7",
    type: "url",
    url: "https://www.bonappetit.com/recipe/spicy-miso-ramen",
    title: "30-Minute Spicy Miso Ramen",
    notes: null,
    content: null,
    status: "READY",
    tags: ["recipe", "ramen", "quick-meals"],
    collections: ["recipes"],
    domain: "bonappetit.com",
    image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800&h=400&fit=crop",
    description: "Quick and flavorful miso ramen that rivals your favorite restaurant. Perfect for busy weeknights.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-8",
    type: "url",
    url: "https://www.kingarthurbaking.com/recipes/sourdough-bread",
    title: "Beginner's Sourdough Bread",
    notes: "Started my starter last week. Can't wait to try this!",
    content: null,
    status: "READY",
    tags: ["recipe", "bread", "sourdough"],
    collections: ["recipes"],
    domain: "kingarthurbaking.com",
    image: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&h=400&fit=crop",
    description: "Master the art of sourdough bread baking with this comprehensive beginner's guide.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // YouTube Videos
  {
    id: "card-9",
    type: "url",
    url: "https://youtube.com/watch?v=example1",
    title: "Building a SaaS from Scratch - Full Course",
    notes: "Great overview of the entire stack. Bookmarked timestamps: 12:34, 45:20, 1:23:10",
    content: null,
    status: "READY",
    tags: ["video", "tutorial", "saas"],
    collections: ["videos", "learning"],
    domain: "youtube.com",
    image: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=400&fit=crop",
    description: "Complete guide to building a SaaS application from scratch using Next.js, Stripe, and more.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-10",
    type: "url",
    url: "https://youtube.com/watch?v=example2",
    title: "Advanced TypeScript Patterns",
    notes: null,
    content: null,
    status: "READY",
    tags: ["video", "typescript", "programming"],
    collections: ["videos", "learning"],
    domain: "youtube.com",
    image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=400&fit=crop",
    description: "Deep dive into advanced TypeScript patterns, generics, and type system features.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Products
  {
    id: "card-11",
    type: "url",
    url: "https://www.amazon.com/product/example1",
    title: "Mechanical Keyboard - Cherry MX Blue",
    notes: "Waiting for Black Friday sale. Compare with Leopold FC660M.",
    content: null,
    status: "READY",
    tags: ["product", "keyboard", "shopping"],
    collections: ["shopping"],
    domain: "amazon.com",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&h=400&fit=crop",
    description: "Premium mechanical keyboard with Cherry MX Blue switches. Perfect for typing and gaming.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-12",
    type: "url",
    url: "https://www.amazon.com/product/example2",
    title: "Ergonomic Office Chair - Herman Miller Aeron",
    notes: "Investment piece. Check local listings for used options.",
    content: null,
    status: "READY",
    tags: ["product", "furniture", "office"],
    collections: ["shopping"],
    domain: "amazon.com",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&h=400&fit=crop",
    description: "The iconic Herman Miller Aeron chair. Premium ergonomics for all-day comfort.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-13",
    type: "url",
    url: "https://www.bhphotovideo.com/camera/example",
    title: "Sony A7 IV Mirrorless Camera",
    notes: null,
    content: null,
    status: "READY",
    tags: ["product", "camera", "photography"],
    collections: ["shopping"],
    domain: "bhphotovideo.com",
    image: "https://images.unsplash.com/photo-1606980394954-d2bf2f69efcd?w=800&h=400&fit=crop",
    description: "Professional mirrorless camera with incredible autofocus and video capabilities.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Travel & Inspiration
  {
    id: "card-14",
    type: "url",
    url: "https://www.lonelyplanet.com/japan/kyoto",
    title: "Complete Guide to Kyoto: Temples, Gardens & Food",
    notes: "Planning trip for spring 2025. Must visit: Fushimi Inari, Arashiyama Bamboo Grove.",
    content: null,
    status: "READY",
    tags: ["travel", "japan", "planning"],
    collections: ["travel"],
    domain: "lonelyplanet.com",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=400&fit=crop",
    description: "Comprehensive guide to exploring Kyoto's ancient temples, stunning gardens, and incredible food scene.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-15",
    type: "url",
    url: "https://www.nomadicmatt.com/travel-blogs/iceland-budget-travel/",
    title: "Iceland on a Budget: Complete Travel Guide",
    notes: null,
    content: null,
    status: "READY",
    tags: ["travel", "iceland", "budget"],
    collections: ["travel"],
    domain: "nomadicmatt.com",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&h=400&fit=crop",
    description: "How to experience Iceland's natural wonders without breaking the bank. Tips on accommodation, food, and transportation.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Productivity & Life
  {
    id: "card-16",
    type: "url",
    url: "https://nesslabs.com/time-management",
    title: "Time Management for Makers: Deep Work Strategies",
    notes: "Implementing the 'maker schedule' starting next week. Block morning for deep work.",
    content: null,
    status: "READY",
    tags: ["productivity", "time-management", "deep-work"],
    collections: ["productivity"],
    domain: "nesslabs.com",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=400&fit=crop",
    description: "How to structure your day for maximum creative output and minimize context switching.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-17",
    type: "url",
    url: "https://jamesclear.com/habit-guide",
    title: "The Ultimate Guide to Building Better Habits",
    notes: null,
    content: null,
    status: "READY",
    tags: ["habits", "self-improvement", "productivity"],
    collections: ["productivity"],
    domain: "jamesclear.com",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=400&fit=crop",
    description: "Evidence-based strategies for forming good habits and breaking bad ones.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // AI & Machine Learning
  {
    id: "card-18",
    type: "url",
    url: "https://openai.com/research/gpt-4",
    title: "GPT-4 Technical Report",
    notes: "Key insights: multimodal capabilities, improved reasoning, safety considerations.",
    content: null,
    status: "READY",
    tags: ["ai", "ml", "research"],
    collections: ["ai-ml"],
    domain: "openai.com",
    image: "https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=800&h=400&fit=crop",
    description: "Official technical report on GPT-4's capabilities, limitations, and architectural improvements.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-19",
    type: "url",
    url: "https://huggingface.co/blog/fine-tune-llm",
    title: "How to Fine-Tune Large Language Models",
    notes: null,
    content: null,
    status: "READY",
    tags: ["ai", "llm", "tutorial"],
    collections: ["ai-ml", "learning"],
    domain: "huggingface.co",
    image: "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&h=400&fit=crop",
    description: "Step-by-step guide to fine-tuning LLMs on your own data using modern techniques like LoRA.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Business & Startups
  {
    id: "card-20",
    type: "url",
    url: "https://paulgraham.com/ds.html",
    title: "Do Things that Don't Scale",
    notes: "Classic essay. Key takeaway: manual work early on helps you understand users.",
    content: null,
    status: "READY",
    tags: ["startups", "business", "essay"],
    collections: ["business"],
    domain: "paulgraham.com",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop",
    description: "Paul Graham's classic essay on why founders should do unscalable things in the early stages.",
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-21",
    type: "url",
    url: "https://www.indiehackers.com/post/how-i-got-to-10k-mrr",
    title: "How I Built a $10K/Month SaaS as a Solo Founder",
    notes: "Inspiring story. Marketing tactics: SEO + content, Reddit, Twitter.",
    content: null,
    status: "READY",
    tags: ["indie-hacking", "saas", "business"],
    collections: ["business"],
    domain: "indiehackers.com",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop",
    description: "A solo founder's journey from idea to $10K MRR, including marketing strategies and lessons learned.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Health & Fitness
  {
    id: "card-22",
    type: "url",
    url: "https://www.strengthlog.com/5x5-workout/",
    title: "StrongLifts 5x5: Complete Beginner's Guide",
    notes: "Starting this program next month. 3x/week, focus on form first.",
    content: null,
    status: "READY",
    tags: ["fitness", "strength-training", "health"],
    collections: ["health"],
    domain: "strengthlog.com",
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=400&fit=crop",
    description: "Simple and effective strength training program for beginners. Build muscle and strength with compound lifts.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-23",
    type: "url",
    url: "https://examine.com/nutrition/protein-intake/",
    title: "How Much Protein Do You Really Need?",
    notes: null,
    content: null,
    status: "READY",
    tags: ["nutrition", "protein", "health"],
    collections: ["health"],
    domain: "examine.com",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&h=400&fit=crop",
    description: "Science-based guide to protein requirements for different goals and activity levels.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Additional items to reach 30
  {
    id: "card-24",
    type: "url",
    url: "https://github.com/awesome-selfhosted/awesome-selfhosted",
    title: "Awesome Self-Hosted: Free Software Network Services",
    notes: "Looking into NextCloud and Bitwarden self-hosting.",
    content: null,
    status: "READY",
    tags: ["self-hosting", "open-source", "tools"],
    collections: ["tech-articles"],
    domain: "github.com",
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=400&fit=crop",
    description: "Curated list of network services and web applications which can be hosted on your own servers.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-25",
    type: "url",
    url: "https://css-tricks.com/css-grid-guide/",
    title: "A Complete Guide to CSS Grid",
    notes: null,
    content: null,
    status: "READY",
    tags: ["css", "web-dev", "grid"],
    collections: ["tech-articles"],
    domain: "css-tricks.com",
    image: "https://images.unsplash.com/photo-1523437113738-bbd3cc89fb19?w=800&h=400&fit=crop",
    description: "Comprehensive guide to CSS Grid layout with examples and use cases.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-26",
    type: "url",
    url: "https://www.nytimes.com/cooking/recipes/chocolate-chip-cookies",
    title: "The Best Chocolate Chip Cookies",
    notes: "NYT recipe is legendary. Use brown butter for extra flavor!",
    content: null,
    status: "READY",
    tags: ["recipe", "dessert", "baking"],
    collections: ["recipes"],
    domain: "nytimes.com",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=400&fit=crop",
    description: "The famous New York Times chocolate chip cookie recipe. Crispy edges, chewy center perfection.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-27",
    type: "url",
    url: "https://stripe.com/docs/payments/payment-intents",
    title: "Payment Intents API - Stripe Documentation",
    notes: "Implementation notes: use webhooks for async confirmation, handle 3D Secure.",
    content: null,
    status: "READY",
    tags: ["stripe", "payments", "api"],
    collections: ["tech-articles"],
    domain: "stripe.com",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=800&h=400&fit=crop",
    description: "Complete guide to implementing Stripe Payment Intents for secure payment processing.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-28",
    type: "url",
    url: "https://www.atlasoscura.com/articles/hidden-gems-tokyo",
    title: "Tokyo's Hidden Gems: Beyond the Tourist Trail",
    notes: null,
    content: null,
    status: "READY",
    tags: ["travel", "japan", "tokyo"],
    collections: ["travel"],
    domain: "atlasoscura.com",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=400&fit=crop",
    description: "Discover Tokyo's secret spots, hidden temples, and local favorites that most tourists miss.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-29",
    type: "url",
    url: "https://www.producthunt.com/posts/raycast",
    title: "Raycast - Supercharged Productivity Tool for macOS",
    notes: "Replaced Alfred with this. The extensions are incredible!",
    content: null,
    status: "READY",
    tags: ["productivity", "tools", "macos"],
    collections: ["productivity"],
    domain: "producthunt.com",
    image: "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800&h=400&fit=crop",
    description: "Lightning-fast launcher and productivity tool with powerful extensions for developers.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "card-30",
    type: "url",
    url: "https://blog.samaltman.com/what-i-wish-someone-had-told-me",
    title: "What I Wish Someone Had Told Me",
    notes: "Wisdom from Sam Altman. Key points: optimize for learning, compound interest is real.",
    content: null,
    status: "READY",
    tags: ["career", "advice", "startups"],
    collections: ["business"],
    domain: "blog.samaltman.com",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=400&fit=crop",
    description: "Sam Altman shares career and life lessons learned from building companies and investing in startups.",
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Add a few MD notes
  {
    id: "note-1",
    type: "md-note",
    url: "",
    title: "Project Ideas - Q1 2025",
    notes: null,
    content: `# Project Ideas - Q1 2025

## High Priority

### 1. Personal Knowledge Base
- Build using Next.js + MDX
- Features: bidirectional links, graph view, tags
- Inspiration: Obsidian, Notion
- Timeline: 4-6 weeks

### 2. AI Writing Assistant
- Use OpenAI API
- Features: outline generation, tone adjustment, grammar checking
- Monetization: freemium model
- Timeline: 2-3 weeks

## Medium Priority

### 3. Fitness Tracker Dashboard
- Track workouts, nutrition, sleep
- Data visualization with charts
- Export to CSV
- Timeline: 3-4 weeks

## Backlog

- Recipe management app
- Habit tracking with streaks
- Reading list with notes
`,
    status: "READY",
    tags: ["projects", "planning", "ideas"],
    collections: [],
    domain: null,
    image: null,
    description: null,
    metadata: {},
    articleContent: null,
    pinned: true,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "note-2",
    type: "md-note",
    url: "",
    title: "Meeting Notes - Product Roadmap Discussion",
    notes: null,
    content: `# Product Roadmap Discussion
*Date: ${new Date().toLocaleDateString()}*

## Attendees
- Sarah (Product)
- Mike (Engineering)
- Alex (Design)

## Key Decisions

### Q1 Priorities
1. ✅ Ship mobile responsive design
2. ⏳ Implement dark mode
3. 📋 Add collaboration features

### Feature Requests from Users
- [ ] Bulk import/export
- [ ] Custom themes
- [ ] API access
- [ ] Browser extension

### Technical Debt
- Upgrade to React 19
- Migrate from REST to GraphQL
- Implement proper error tracking

## Action Items
- [ ] Sarah: Create user stories for collab features
- [ ] Mike: Estimate technical debt items
- [ ] Alex: Mockups for dark mode by Friday
`,
    status: "READY",
    tags: ["meetings", "work", "roadmap"],
    collections: [],
    domain: null,
    image: null,
    description: null,
    metadata: {},
    articleContent: null,
    pinned: false,
    deleted: false,
    deletedAt: null,
    inDen: false,
    encryptedContent: null,
    scheduledDate: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Generate fake collections tree
const FAKE_COLLECTIONS: CollectionNode[] = [
  {
    id: "coll-1",
    name: "Tech Articles",
    slug: "tech-articles",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: true,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: true,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-2",
    name: "Design Resources",
    slug: "design-resources",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: true,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: true,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-3",
    name: "Recipes",
    slug: "recipes",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: true,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-4",
    name: "Videos",
    slug: "videos",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-5",
    name: "Learning",
    slug: "learning",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-6",
    name: "Shopping",
    slug: "shopping",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-7",
    name: "Travel",
    slug: "travel",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: true,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: true,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-8",
    name: "Productivity",
    slug: "productivity",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-9",
    name: "AI & ML",
    slug: "ai-ml",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-10",
    name: "Business",
    slug: "business",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
  {
    id: "coll-11",
    name: "Health",
    slug: "health",
    parentId: null,
    coverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=200&fit=crop",
    coverImagePosition: 50,
    pinned: false,
    deleted: false,
    inDen: false,
    isPrivate: false,
    isSystem: false,
    hidePreview: false,
    useCoverAsBackground: false,
    userId: "demo-user",
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    children: [],
  },
];

function DemoPageContent() {
  const setContentType = usePanelStore((state) => state.setContentType);

  // Memoize the fake data
  const items = useMemo(() => FAKE_CARDS, []);
  const collections = useMemo(() => FAKE_COLLECTIONS, []);

  // Set the right panel content to show library controls
  useEffect(() => {
    setContentType("library-controls");
  }, [setContentType]);

  return (
    <LibraryView
      initialCards={items}
      initialNextCursor={undefined}
      collectionsTree={collections}
      query={{}}
      viewMode="normal"
      timelineDays={30}
    />
  );
}

export default function DemoPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <DemoPageContent />
    </Suspense>
  );
}
